const quotes = [
  { text: "A Jnani need not prostrate before anybody nor need he give his blessings to anybody", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/A Jnani need not prostrate before anybody nor need he give his blessings to anybody" },
  { text: "A fire leaps up from our inside like lightning and another fire descends upon us from above", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/A fire leaps up from our inside like lightning and another fire descends upon us from above" },
  { text: "A person’s paradise is developed inside him", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/A person’s paradise is developed inside him" },
  { text: "Abhyasa consists in withdrawal within the Self every time you are disturbed by thought", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Abhyasa consists in withdrawal within the Self every time you are disturbed by thought" },
  { text: "Accept all of the pain pt 2", source: "One Punch Man", slug: "Wisdom-Quotes/Accept all of the pain pt 2" },
  { text: "After some time, Ashtavakra Muni happened to pass that side and, while he was about to take rest und", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/After some time, Ashtavakra Muni happened to pass that side and, while he was about to take rest und" },
  { text: "All effort is only for giving up the notion that we are limited", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/All effort is only for giving up the notion that we are limited" },
  { text: "All that can be done can be done through understanding", source: "Vigyan Bhairav Tantra Volume 1", slug: "Wisdom-Quotes/All that can be done can be done through understanding" },
  { text: "All the concepts you have formed in the past must be discarded and replaced by void", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/All the concepts you have formed in the past must be discarded and replaced by void" },
  { text: "All the sadhana that we do is meant to invoke a strong experiential feeling of belongingness", source: "Swami Ishwarananda Giriji Maharaj", slug: "Wisdom-Quotes/All the sadhana that we do is meant to invoke a strong experiential feeling of belongingness" },
  { text: "And you threw not when you did throw, but it was Allah Who threw", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/And you threw not when you did throw, but it was Allah Who threw" },
  { text: "And you, O soul at peace! Return to your Lord well pleased with Him and He well pleased with you", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/And you, O soul at peace! Return to your Lord well pleased with Him and He well pleased with you_" },
  { text: "Arpana offering means that the mind gets merged in the self and becomes one with it", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Arpana offering means that the mind gets merged in the self and becomes one with it" },
  { text: "Arpana offering means that the mind gets merged in the self and becomes one with it Part 2", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Arpana offering means that the mind gets merged in the self and becomes one with it Part 2" },
  { text: "Arunachala Ramana is the Paramatma Himself", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Arunachala Ramana is the Paramatma Himself" },
  { text: "Attention to ones own Self is the only raft", source: "Ramana Maharshi", slug: "Wisdom-Quotes/Attention to ones own Self is the only raft" },
  { text: "BHAGAVANS HANDWRITING - There is neither speaker nor thinker in that state; so that transcendental s", source: "Ramana Maharshi", slug: "Wisdom-Quotes/BHAGAVANS HANDWRITING - There is neither speaker nor thinker in that state; so that transcendental s" },
  { text: "Be aware of yourself And accept yourself as you are", source: "Vagabond", slug: "Wisdom-Quotes/Be aware of yourself And accept yourself as you are" },
  { text: "Bhagavan does not intend to deny the necessity or wisdom of taking a reasonable and moderate care of", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/Bhagavan does not intend to deny the necessity or wisdom of taking a reasonable and moderate care of" },
  { text: "Bodhisattvas, together with all wriggling things possessed of life, share in this great Nirvanic nat", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Bodhisattvas, together with all wriggling things possessed of life, share in this great Nirvanic nat" },
  { text: "Brahma-Vidya is nothing other than seeing That which remains", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/Brahma-Vidya  is nothing other than seeing That which remains" },
  { text: "But the prisoner has become too identified with the prison cell", source: "The Perfect Master, Vol 1", slug: "Wisdom-Quotes/But the prisoner has become too identified with the prison cell" },
  { text: "But to prefer God over everything and to accept every hardship of the world", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/But to prefer God over everything and to accept every hardship of the world" },
  { text: "But when we look into the faculties of man and try to discover what is their highest reach, we find", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/But when we look into the faculties of man and try to discover what is their highest reach, we find " },
  { text: "By knowing which all is renounced ever abide as that itself", source: "The Ribhu Gita", slug: "Wisdom-Quotes/By knowing which all is renounced ever abide as that itself.txt" },
  { text: "By whatever path you go you will have to lose yourself in the One", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/By whatever path you go you will have to lose yourself in the One" },
  { text: "Complete erasure of the ego is necessary", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/Complete erasure of the ego is necessary" },
  { text: "Conquering a thousand elephants is nothing beside this Gurus power to conquer the rutting elephants", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/Conquering a thousand elephants is nothing beside this Gurus power to conquer the rutting elephants " },
  { text: "Dharma is neither preached in words nor otherwise signified", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Dharma is neither preached in words nor otherwise signified" },
  { text: "Divine grace still bestows this bounty upon those who seek it", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/Divine grace still bestows this bounty upon those who seek it" },
  { text: "Dont believe your thoughts", source: "Ramana Maharshi", slug: "Wisdom-Quotes/Dont believe your thoughts" },
  { text: "Each gliding along in its orbit", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/Each gliding along in its orbit" },
  { text: "Enter into the silence of the temple", source: "The New Dawn", slug: "Wisdom-Quotes/Enter into the silence of the temple" },
  { text: "Even amidst great action the wise one remains still", source: "Ashtavakra Gita", slug: "Wisdom-Quotes/Even amidst great action the wise one remains still" },
  { text: "First you must throw away all your opinions", source: "Dropping Ashes On the Buddha", slug: "Wisdom-Quotes/First you must throw away all your opinions" },
  { text: "For the extroverted intellect, the means to abide in Self is to begin enquiring inwardly", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/For the extroverted intellect, the means to abide in Self is to begin enquiring inwardly" },
  { text: "Fortunate is the man who does not lose himself in the labyrinths of philosophy", source: "Ramana Maharshi", slug: "Wisdom-Quotes/Fortunate is the man who does not lose himself in the labyrinths of philosophy" },
  { text: "From the day when that light is generated in a person, he ceases to be earthly and becomes heavenly", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/From the day when that light is generated in a person, he ceases to be earthly and becomes heavenly" },
  { text: "Gateway of the Stillness beyond all Activity", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Gateway of the Stillness beyond all Activity" },
  { text: "Give up the desire that tends to bondage and the desire for liberation too", source: "Yoga Vasistha", slug: "Wisdom-Quotes/Give up the desire that tends to bondage and the desire for liberation too.txt" },
  { text: "God has fashioned human nature such that it is like a receptacle that cannot remain empty of some fo", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/God has fashioned human nature such that it is like a receptacle that cannot remain empty of some fo" },
  { text: "Guru is not merely the perfection you wish to conquer", source: "Swami Ishwarananda Giriji Maharaj", slug: "Wisdom-Quotes/Guru is not merely the perfection you wish  to conquer" },
  { text: "Having many sorts of knowledge cannot compare with giving up SEEKING for anything", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Having many sorts of knowledge cannot compare with giving up SEEKING for anything" },
  { text: "He is everywhere unattached and free", source: "Ashtavakra Gita", slug: "Wisdom-Quotes/He is everywhere unattached and free" },
  { text: "He is washed and cleansed and God inscribes love of virtue upon his heart and casts out from it the", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/He is washed and cleansed and God inscribes love of virtue upon his heart and casts out from it the " },
  { text: "He was therefore peaceful in both pain and pleasure", source: "Yoga Vasistha", slug: "Wisdom-Quotes/He was therefore peaceful in both pain and pleasure.txt" },
  { text: "His love upon him and by the meeting of these two loves a light is generated inside the person which", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/His love upon him and by the meeting of these two loves a light is generated inside the person which" },
  { text: "How can one whose innermost heart has been scorched by the sun of sorrow that comes from duty be hap", source: "Ashtavakra Gita", slug: "Wisdom-Quotes/How can one whose innermost heart has been scorched by the sun of sorrow that comes from duty be hap" },
  { text: "I falsely imagined till now that all these which are yours", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/I falsely imagined till now that all these which are yours" },
  { text: "If all the false ideas and impressions are swept away and thrown out what remains is a feeling of pl", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/If all the false ideas and impressions are swept away and thrown out what remains is a feeling of pl" },
  { text: "If only you will avoid concepts of existence and non-existence in regard to absolutely everything yo", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/If only you will avoid concepts of existence and non-existence in regard to absolutely everything yo" },
  { text: "If the ego and all its experiences are dismissed as passing shadows the ever present ultimate realit", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/If the ego and all its experiences are dismissed as passing shadows the ever present ultimate realit" },
  { text: "If you wish to experience Enlightenment yourselves you must not indulge in such conceptions", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/If you wish to experience Enlightenment yourselves you must not indulge in such conceptions.txt" },
  { text: "In olden days, when we were doing the cooking during summer, we used to have a pot into which we put", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/In olden days, when we were doing the cooking during summer, we used to have a pot into which we put" },
  { text: "In order to understand the illnesses of sentient beings, one should not abide in the unconditioned;", source: "The Vimalakirti Sutra", slug: "Wisdom-Quotes/In order to understand the illnesses of sentient beings, one should not abide in the unconditioned; " },
  { text: "In the deep sleep state we lay down our ego", source: "Ramana Maharshi", slug: "Wisdom-Quotes/In the deep sleep state we lay down our ego" },
  { text: "It is enough if the mind is kept one pointed in vichara dhyana japa and parayana", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/It is enough if the mind is kept one pointed in vichara dhyana japa and parayana" },
  { text: "It is impossible for someone with bonds to emancipate others from their bonds", source: "The Vimalakirti Sutra", slug: "Wisdom-Quotes/It is impossible for someone with bonds to emancipate others from their bonds" },
  { text: "It is only living a thing totally that one transcends it", source: "The Perfect Master, Vol 1", slug: "Wisdom-Quotes/It is only living a thing totally that one transcends it" },
  { text: "It is true wisdom for the mind to turn away From outer objects and behold Its own effulgent form", source: "Ramana Maharshi", slug: "Wisdom-Quotes/It is true wisdom for the mind to turn away From outer objects and behold Its own effulgent form" },
  { text: "Knowing through the senses only the objects of form and quality before it —- the means to abide in S", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/Knowing through the senses only the objects of form and quality before it —- the means to abide in S" },
  { text: "Knowledge is of three kinds", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/Knowledge is of three kinds" },
  { text: "Let not a day pass without communion with nature which is so divine", source: "Swami Ishwarananda Giriji Maharaj", slug: "Wisdom-Quotes/Let not a day pass without communion with nature which is so divine" },
  { text: "Let us change our attitudes and absorb ourselves not in happenings", source: "Swami Ishwarananda Giriji Maharaj", slug: "Wisdom-Quotes/Let us change our attitudes and absorb ourselves not in happenings" },
  { text: "Liberation is not had except through the cessation of all notions", source: "Yoga Vasistha", slug: "Wisdom-Quotes/Liberation is not had except through the cessation of all notions" },
  { text: "Like the sky he provides shelter under his shade", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/Like the sky he provides shelter under his shade" },
  { text: "Lord, good sons and daughters who have abandoned these three (body, life, and wealth) and have accep", source: "The Sutra of Queen Srimala", slug: "Wisdom-Quotes/Lord, good sons and daughters who have abandoned these three (body, life, and wealth) and have accep" },
  { text: "Lord, which of us is the clevererIf You have given Yourself up to me, I enjoy endless bliss, but of", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Lord, which of us is the clevererIf You have given Yourself up to me, I enjoy endless bliss, but of " },
  { text: "Most people are so totally identified with their strong feelings of likes and dislikes that they are", source: "Swami Ishwarananda Giriji Maharaj", slug: "Wisdom-Quotes/Most people are so totally identified with their strong feelings of likes and dislikes that they are" },
  { text: "My state never felt the creation and dissolution of the universe", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/My state never felt the creation and dissolution of the universe" },
  { text: "O mind, it is not wise for you to come out (in the form of thoughts) it is best to go within. Hide y", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/O mind, it is not wise for you to come out (in the form of thoughts) it is best to go within. Hide y" },
  { text: "O you that ridicule idol-worship", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/O you that ridicule idol-worship" },
  { text: "O you that ridicule idol-worship, having not discovered through heart-melting love its secret, how i", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/O you that ridicule idol-worship, having not discovered through heart-melting love its secret, how i" },
  { text: "Om Namo Bhagavate Sri Ramanaya", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/Om Namo Bhagavate Sri Ramanaya" },
  { text: "One may find hatha yoga suitable and another man nama japa", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/One may find hatha yoga suitable and another man nama japa" },
  { text: "One should stand straight and firm despite one’s helplessness and weakness and lack of comfort from", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/One should stand straight and firm despite one’s helplessness and weakness and lack of comfort from " },
  { text: "One’s fear and quaking of one’s body while one is entering samadhi is due", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/One’s fear and quaking of one’s body while one is entering samadhi is due" },
  { text: "Only one who is unattached things earthly and heavenly alike can attain to Divine Knowledge", source: "The Incredible Sai Baba", slug: "Wisdom-Quotes/Only one who is unattached things earthly and heavenly alike can attain to Divine Knowledge" },
  { text: "Only when your minds cease dwelling upon anything whatsoever will you come to an understanding of th", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Only when your minds cease dwelling upon anything whatsoever will you come to an understanding of th" },
  { text: "Our original Buddha-Nature is, in highest truth, devoid of any atom of objectivity", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Our original Buddha-Nature is, in highest truth, devoid of any atom of objectivity_" },
  { text: "Peace is the inner nature of humankind", source: "Ramana Maharshi", slug: "Wisdom-Quotes/Peace is the inner nature of humankind" },
  { text: "Poem - The nature of the Mind when understood", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Poem - The nature of the Mind when understood" },
  { text: "Power of Supreme Silence which consumes all by remaining as mere Existence-Self-Consciousness", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/Power of Supreme Silence which consumes all by remaining as mere Existence-Self-Consciousness" },
  { text: "Present bondages are said to be of four types", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Present bondages are said to be of four types" },
  { text: "Ramana Bhagavan attained jnana without any effort in an ordinary house in a narrow lane in the centr", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Ramana Bhagavan attained jnana without any effort in an ordinary house in a narrow lane in the centr" },
  { text: "Rare is the one who believes nothing and is never confused", source: "Ashtavakra Gita", slug: "Wisdom-Quotes/Rare is the one who believes nothing and is never confused" },
  { text: "Realisation now consists in getting rid of this false idea that one is not realised", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Realisation now consists in getting rid of this false idea that one is not realised" },
  { text: "Satguru Parabrahman is all love for no- knowingness", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/Satguru Parabrahman is all love for no- knowingness" },
  { text: "See everything in its entirety to truely see", source: "Vagabond", slug: "Wisdom-Quotes/See everything in its entirety to truely see" },
  { text: "Seek the conquest of the mind and self-control which are the fruits of wisdom", source: "Yoga Vasistha", slug: "Wisdom-Quotes/Seek the conquest of the mind and self-control which are the fruits of wisdom" },
  { text: "Self-surrender is the same as Self-knowledge", source: "Ramana Maharshi", slug: "Wisdom-Quotes/Self-surrender is the same as Self-knowledge" },
  { text: "Seven stages of knowledge which bestow Liberation", source: "Kaivalya Navaneetam", slug: "Wisdom-Quotes/Seven stages of knowledge which bestow Liberation" },
  { text: "So many things in this world cannot be expressed with words. Some things can not be explained", source: "Vagabond", slug: "Wisdom-Quotes/So many things in this world cannot be expressed with words. Some things can not be explained" },
  { text: "Suppose I ask you to go and wake all those people up in the dream and tell them they are not real. W", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/Suppose I ask you to go and wake all those people up in the dream and tell them they are not real. W" },
  { text: "Supreme Devotion that flares up with the merging of the ego into the Light of Supreme Stillness", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/Supreme Devotion that flares up with the merging of the ego into the Light of Supreme Stillness" },
  { text: "The Four Principles of Self Realization", source: "Silence of the Heart", slug: "Wisdom-Quotes/The Four Principles of Self Realization" },
  { text: "The Four Principles part 3", source: "Silence of the Heart", slug: "Wisdom-Quotes/The Four Principles part 3" },
  { text: "The Four Principles part 4", source: "Silence of the Heart", slug: "Wisdom-Quotes/The Four Principles part 4" },
  { text: "The Operation of the Practical Ordinances of the Law", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/The Operation of the Practical Ordinances of the Law" },
  { text: "The answers to any questions that are put to you will emerge like an echo from within and they will", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/The answers to any questions that are put to you will emerge like an echo from within and they will " },
  { text: "The approach to it is called the Gateway of the Stillness beyond all Activity", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/The approach to it is called the Gateway of the Stillness beyond all Activity" },
  { text: "The dangerous path - identify with EVERYTHING", source: "The New Dawn", slug: "Wisdom-Quotes/The dangerous path - identify with EVERYTHING" },
  { text: "The distress of the mind is got rid of by enquiry into the nature of the self", source: "Yoga Vasistha", slug: "Wisdom-Quotes/The distress of the mind is got rid of by enquiry into the nature of the self.txt" },
  { text: "The fool thinks peace comes by controlling the mind", source: "Ashtavakra Gita", slug: "Wisdom-Quotes/The fool thinks peace comes by controlling the mind" },
  { text: "The four principles of Enlightenment", source: "Silence of the Heart", slug: "Wisdom-Quotes/The four principles of Enlightenment" },
  { text: "The four principles part 2", source: "Silence of the Heart", slug: "Wisdom-Quotes/The four principles part 2" },
  { text: "The greatest form of ego for an individual is to present himself as a teacher and become a guru", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/The greatest form of ego for an individual is to present himself as a teacher and become a guru" },
  { text: "The king said that he was at the very moment placing at the feet of the Guru his body, his mind, his", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/The king said that he was at the very moment placing at the feet of the Guru his body, his mind, his" },
  { text: "The loneliness transforms into aloneness", source: "The New Dawn", slug: "Wisdom-Quotes/The loneliness transforms into aloneness" },
  { text: "The naked light in a windless place", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/The naked light in a windless place" },
  { text: "The only worthy occupation is to thoroughly absorb the ego by turning Selfward and, without allowing", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/The only worthy occupation is to thoroughly absorb the ego by turning Selfward and, without allowing" },
  { text: "The real worship of him is to be in mouna (silence)", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/The real worship of him is to be in mouna (silence)" },
  { text: "The relinquishment of ALL delusions leaves no Dharma on which to lay hold", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/The relinquishment of ALL delusions leaves no Dharma on which to lay hold" },
  { text: "The same disgusting pleasures are experienced and the same acts are repeated day after day in this w", source: "Yoga Vasistha", slug: "Wisdom-Quotes/The same disgusting pleasures are experienced and the same acts are repeated day after day in this w" },
  { text: "The three kinds of relinquishment", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/The three kinds of relinquishment" },
  { text: "Then from some left-overs amongst our things, he took out some limes and squeezed the juice into the", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Then from some left-overs amongst our things, he took out some limes and squeezed the juice into the" },
  { text: "There are three kinds of relinquishment", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/There are three kinds of relinquishment" },
  { text: "There is unbroken flow of peace and the heart is filled with the bliss of the absolute,", source: "Yoga Vasistha", slug: "Wisdom-Quotes/There is unbroken flow of peace and the heart is filled with the bliss of the absolute," },
  { text: "These are the three states of spiritual ranks", source: "Haqiqatul-Wahi - The Philosophy of Divine Revelation", slug: "Wisdom-Quotes/These are the three states of spiritual ranks" },
  { text: "They teach the three emancipations of emptiness, signlessness, wishlessness and nonactivation", source: "The Vimalakirti Sutra", slug: "Wisdom-Quotes/They teach the three emancipations of emptiness, signlessness, wishlessness and nonactivation" },
  { text: "This bounty is most rare and is the height of good fortune. For him on whom it is bestowed everythin", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/This bounty is most rare and is the height of good fortune. For him on whom it is bestowed everythin" },
  { text: "This chapter deals with all the preparatory steps which were needed before the creation of bio-units", source: "Revelation, Rationality, Knowledge & Truth", slug: "Wisdom-Quotes/This chapter deals with all the preparatory steps which were needed before the creation of bio-units" },
  { text: "This verse clearly proclaims that those people who were nurtured in this life on the love of God", source: "The Philosophy of the Teachings of Islam", slug: "Wisdom-Quotes/This verse clearly proclaims that those people who were nurtured in this life on the love of God" },
  { text: "Those alone are good actions karmas which are done lovingly and with a peaceful and pure mind", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/Those alone are good actions karmas which are done lovingly and with a peaceful and pure mind" },
  { text: "Those who seek the Dharma must not seek from the Buddha", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Those who seek the Dharma must not seek from the Buddha" },
  { text: "Three ways to describe truth - The same truth has to be expressed in different ways to suit the capa", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/Three ways to describe truth - The same truth has to be expressed in different ways to suit the capa" },
  { text: "To arrest the mind — which tries to rush outwards — securely within, is the truly heroic act of the", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/To arrest the mind — which tries to rush outwards — securely within, is the truly heroic act of the " },
  { text: "To enjoy the fruits of the worship of the feet of the moon-crested Lord Siva", source: "The Ribhu Gita", slug: "Wisdom-Quotes/To enjoy the fruits of the worship of the feet of the moon-crested Lord Siva" },
  { text: "To perform one’s duty carefully is the greatest service to God", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/To perform one’s duty carefully is the greatest service to God" },
  { text: "To put out of mind even the principle from which action springs is the true teaching of the Buddhas", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/To put out of mind even the principle from which action springs is the true teaching of the Buddhas" },
  { text: "Transform your intelligence into the purest of paper", source: "Guru Granth Sahib", slug: "Wisdom-Quotes/Transform your intelligence into the purest of paper" },
  { text: "Transforming yourself is a means of giving light to the whole world", source: "Ramana Maharshi", slug: "Wisdom-Quotes/Transforming yourself is a means of giving light to the whole world" },
  { text: "Transforming yourself is a means of giving light to the whole world2", source: "Ramana Maharshi", slug: "Wisdom-Quotes/Transforming yourself is a means of giving light to the whole world2" },
  { text: "What is a bodhisattva who does not abide in the unconditioned", source: "The Vimalakirti Sutra", slug: "Wisdom-Quotes/What is a bodhisattva who does not abide in the unconditioned_" },
  { text: "What is it to have skillful means with ones wisdom emancipated", source: "The Vimalakirti Sutra", slug: "Wisdom-Quotes/What is it to have skillful means with ones wisdom emancipated" },
  { text: "When I once complained to Bhagavan about Chinna Swami, he instantly corrected me and I steadily stoo", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/When I once complained to Bhagavan about Chinna Swami, he instantly corrected me and I steadily stoo" },
  { text: "When a person reaches a certain stage and becomes fit for enlightenment", source: "Ramana Maharshi", slug: "Wisdom-Quotes/When a person reaches a certain stage and becomes fit for enlightenment" },
  { text: "When all these are stilled", source: "Ramana Maharshi", slug: "Wisdom-Quotes/When all these are stilled" },
  { text: "When you are very quiet you have arrived at the basis of everything", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/When you are very quiet you have arrived at the basis of everything" },
  { text: "Where is the place of enlightenment", source: "The Vimalakirti Sutra", slug: "Wisdom-Quotes/Where is the place of enlightenment" },
  { text: "Why look outward and go on explaining the phenomena which are endless", source: "Ramana Maharshi", slug: "Wisdom-Quotes/Why look outward and go on explaining the phenomena which are endless" },
  { text: "With what identity would you like to quit this world", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/With what identity would you like to quit this world" },
  { text: "You are asking Who am I and you are not going to get an answer because the one who will get the answ", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/You are asking Who am I and you are not going to get an answer because the one who will get the answ" },
  { text: "You are not a foreigner in existence", source: "The New Dawn", slug: "Wisdom-Quotes/You are not a foreigner in existence" },
  { text: "You are the constant illumination that lights up both the experiences and the void", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/You are the constant illumination that lights up both the experiences and the void" },
  { text: "You begin to inquire. To whom do all these thoughts come", source: "Silence of the Heart", slug: "Wisdom-Quotes/You begin to inquire. To whom do all these thoughts come" },
  { text: "You can only perceive what true strength is when you yourself become truly strong", source: "Vagabond", slug: "Wisdom-Quotes/You can only perceive what true strength is when you yourself become truly strong" },
  { text: "You have been given guidance through innate disposition", source: "Early Islamic Mysticism", slug: "Wisdom-Quotes/You have been given guidance through innate disposition" },
  { text: "You who intend to celebrate the birthday", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/You who intend to celebrate the birthday" },
]

document.addEventListener("nav", () => {
  const container = document.getElementById("random-quote")
  if (!container) return

  const q = quotes[Math.floor(Math.random() * quotes.length)]
  const quoteEl = document.getElementById("random-quote-text")
  const sourceEl = document.getElementById("random-quote-source")
  const linkEl = document.getElementById("random-quote-link") as HTMLAnchorElement | null
  if (!quoteEl || !sourceEl) return

  quoteEl.textContent = q.text
  sourceEl.textContent = "\u2014 " + q.source
  if (linkEl) linkEl.href = "/" + q.slug
})
