const quotes = [
  { text: "After enlightenment nothing happens all happening stops...", source: "The Perfect Master, Vol 1", slug: "Wisdom-Quotes/After enlightenment nothing happens all happening stops disappears" },
  { text: "After renouncing everything you have come to this forest", source: "Tripura Rahasya", slug: "Wisdom-Quotes/After renouncing everything you have come to this forest" },
  { text: "After self-realization behavior expresses itself...", source: "The Nectar of Immortality", slug: "Wisdom-Quotes/After self-realization behavior expresses itself spontaneously" },
  { text: "All being only Consciousness the name all does not exist", source: "The Ribhu Gita", slug: "Wisdom-Quotes/All being only Consciousness the name all does not exist" },
  { text: "All it required was water and love", source: "Dune", slug: "Wisdom-Quotes/All it required was water and love" },
  { text: "All that is required is to be still", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/All that is required is to be still" },
  { text: "All the pentads to be contemplated", source: "The Ribhu Gita", slug: "Wisdom-Quotes/All the pentads to be contemplated" },
  { text: "All these things are within the Self", source: "Tripura Rahasya", slug: "Wisdom-Quotes/All these things are within the Self" },
  { text: "Are there degrees of illusion", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Are there degrees of illusion" },
  { text: "Arunachala means Aruna-achala being unmoved", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/Arunachala means Aruna-achala being unmoved" },
  { text: "Ashtavakra said seeing hearing touching smelling the...", source: "Ashtavakra Gita", slug: "Wisdom-Quotes/Ashtavakra said seeing hearing touching smelling the wise one is free" },
  { text: "Ashtavakra said the wise one is content with whatever comes", source: "Ashtavakra Gita", slug: "Wisdom-Quotes/Ashtavakra said the wise one is content with whatever comes" },
  { text: "Awareness is the one necessary factor states without...", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Awareness is the one necessary factor states without awareness do not lead to Moksha" },
  { text: "Be as you are the Self is the real book life the written...", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/Be as you are the Self is the real book life the written pages" },
  { text: "Because I am not happy otherwise", source: "Tripura Rahasya", slug: "Wisdom-Quotes/Because I am not happy otherwise" },
  { text: "Bhagavan asked who is the questioner and what is the Self", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Bhagavan asked who is the questioner and what is the Self" },
  { text: "Bhagavan discoursed on the nature of the heart", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/Bhagavan discoursed on the nature of the heart" },
  { text: "Bhagavan rarely asked anyone for anything", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/Bhagavan rarely asked anyone for anything" },
  { text: "Bhagavan said his state of being was beyond subject and...", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Bhagavan said his state of being was beyond subject and object" },
  { text: "Bhagavan spoke about the nature of jnana", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/Bhagavan spoke about the nature of jnana" },
  { text: "Bhagiratha met his preceptor and the two meditated in...", source: "Yoga Vasistha", slug: "Wisdom-Quotes/Bhagiratha met his preceptor and the two meditated in silence" },
  { text: "Blame self exaggerate faults", source: "\"", slug: "Wisdom-Quotes/Blame self exaggerate faults" },
  { text: "Bondages of the past the future and the present", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Bondages of the past the future and the present" },
  { text: "Both experience and experiencer will disappear", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/Both experience and experiencer will disappear" },
  { text: "By mercy is really meant not conceiving of a Buddha to...", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/By mercy is really meant not conceiving of a Buddha to be Enlightened" },
  { text: "By way of paying homage to Robert", source: "Silence of the Heart", slug: "Wisdom-Quotes/By way of paying homage to Robert" },
  { text: "Can you prove one can become Realized in the time it...", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Can you prove one can become Realized in the time it takes to mount a horse" },
  { text: "Chudala saw her husbands mind and knew his state", source: "Tripura Rahasya", slug: "Wisdom-Quotes/Chudala saw her husbands mind and knew his state" },
  { text: "Church and State scientific reason and faith", source: "Dune", slug: "Wisdom-Quotes/Church and State scientific reason and faith" },
  { text: "Complete surrender is prescribed do that first then see...", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/Complete surrender is prescribed do that first then see for yourself" },
  { text: "Consciousness alone exists consciousness alone is all this", source: "Yoga Vasistha", slug: "Wisdom-Quotes/Consciousness alone exists consciousness alone is all this" },
  { text: "Despite so much development taking place sorrow has not...", source: "\"", slug: "Wisdom-Quotes/Despite so much development taking place sorrow has not decreased" },
  { text: "Detachment from worldly desires leads to liberation", source: "Kaivalya Navaneetam", slug: "Wisdom-Quotes/Detachment from worldly desires leads to liberation" },
  { text: "Do not be so sorrow stricken the master takes care", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Do not be so sorrow stricken the master takes care" },
  { text: "Do not exploit this gift do not try to use it for...", source: "Greater Community Spirituality", slug: "Wisdom-Quotes/Do not exploit this gift do not try to use it for personal advantage" },
  { text: "Do not permit the events of your daily lives to bind you", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Do not permit the events of your daily lives to bind you" },
  { text: "Does your mother ever talk about morality and ethics", source: "Dune", slug: "Wisdom-Quotes/Does your mother ever talk about morality and ethics" },
  { text: "Dont act out of your knowledge but act out of your...", source: "\"", slug: "Wisdom-Quotes/Dont act out of your knowledge but act out of your consciousness" },
  { text: "Endowed with discrimination and dispassion", source: "Yoga Vasistha", slug: "Wisdom-Quotes/Endowed with discrimination and dispassion" },
  { text: "Enquiry is not the only way", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Enquiry is not the only way" },
  { text: "Even the clearest understanding is not enough one must work", source: "In Search of the Miraculous", slug: "Wisdom-Quotes/Even the clearest understanding is not enough one must work" },
  { text: "Five thousand years of human minds evolution has not...", source: "The New Dawn", slug: "Wisdom-Quotes/Five thousand years of human minds evolution has not demystified existence" },
  { text: "Food consecration mantra from the Bhagavad Gita", source: "Bhagavad Gita", slug: "Wisdom-Quotes/Food consecration mantra from the Bhagavad Gita" },
  { text: "Fremen were the first humans to develop a consciousness...", source: "Dune", slug: "Wisdom-Quotes/Fremen were the first humans to develop a consciousness marching" },
  { text: "Give up names and forms and meditate", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Give up names and forms and meditate" },
  { text: "God has His own plans and all these go on according to that", source: "Ramana Maharshi", slug: "Wisdom-Quotes/God has His own plans and all these go on according to that" },
  { text: "Gratitude is meditation being silently here now and the...", source: "The New Dawn", slug: "Wisdom-Quotes/Gratitude is meditation being silently here now and the whole opens up" },
  { text: "Having many sorts of knowledge cannot compare with...", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Having many sorts of knowledge cannot compare with giving up seeking" },
  { text: "Having recognised oneself as the ocean the sage walks in...", source: "Ashtavakra Gita", slug: "Wisdom-Quotes/Having recognised oneself as the ocean the sage walks in peace" },
  { text: "He could not move as the force of Bhagavans presence...", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/He could not move as the force of Bhagavans presence held him" },
  { text: "He is the ocean of love and sympathy", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/He is the ocean of love and sympathy" },
  { text: "He who is always in pursuit of happiness but finds only...", source: "\"", slug: "Wisdom-Quotes/He who is always in pursuit of happiness but finds only sorrow" },
  { text: "He who stands rooted in self-knowledge is liberated here...", source: "Yoga Vasistha", slug: "Wisdom-Quotes/He who stands rooted in self-knowledge is liberated here and now" },
  { text: "His greatness was like red hot coal hidden in embers", source: "Tripura Rahasya", slug: "Wisdom-Quotes/His greatness was like red hot coal hidden in embers" },
  { text: "His memory was like an omnipresent prism of prescience", source: "Dune", slug: "Wisdom-Quotes/His memory was like an omnipresent prism of prescience" },
  { text: "His obsession with trade approached delirium", source: "A Very Special Patron - Saint Anthony Mary Claret", slug: "Wisdom-Quotes/His obsession with trade approached delirium" },
  { text: "His vocational detour to the Society of Jesus had not...", source: "A Very Special Patron - Saint Anthony Mary Claret", slug: "Wisdom-Quotes/His vocational detour to the Society of Jesus had not been without purpose" },
  { text: "How shall I overcome my passions", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/How shall I overcome my passions" },
  { text: "How to gain Divine Grace", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/How to gain Divine Grace" },
  { text: "How to know the Real I as distinct from the false I", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/How to know the Real I as distinct from the false I" },
  { text: "I am Brahman there is no doubt of this abide in Silence...", source: "The Ribhu Gita", slug: "Wisdom-Quotes/I am Brahman there is no doubt of this abide in Silence at ease" },
  { text: "I am cool you throw fire at me and it becomes cool", source: "The Perfect Master, Vol 1", slug: "Wisdom-Quotes/I am cool you throw fire at me and it becomes cool" },
  { text: "I am not the individual soul there are no differences", source: "The Ribhu Gita", slug: "Wisdom-Quotes/I am not the individual soul there are no differences" },
  { text: "I chose the milk and was told you have chosen well", source: "Early Islamic Mysticism", slug: "Wisdom-Quotes/I chose the milk and was told you have chosen well" },
  { text: "I exist is the only permanent self-evident experience of...", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/I exist is the only permanent self-evident experience of everyone" },
  { text: "I have not found such great faith even in Israel", source: "Bible - Book of Luke", slug: "Wisdom-Quotes/I have not found such great faith even in Israel" },
  { text: "I told consciousness it is you who is suffering not I", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/I told consciousness it is you who is suffering not I" },
  { text: "If Love is an attribute of the Self why is the world so...", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/If Love is an attribute of the Self why is the world so miserable" },
  { text: "If knowledge is given to all nobody will gain anything", source: "In Search of the Miraculous", slug: "Wisdom-Quotes/If knowledge is given to all nobody will gain anything" },
  { text: "If somebody comes back from Ramanashramam and does not...", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/If somebody comes back from Ramanashramam and does not talk about Bhagavan" },
  { text: "If something appeared to one who has not attained...", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/If something appeared to one who has not attained realization" },
  { text: "If you become the truth the problem will take care of itself", source: "Silence of the Heart", slug: "Wisdom-Quotes/If you become the truth the problem will take care of itself" },
  { text: "If you know yourself it will take care of the person", source: "Silence of the Heart", slug: "Wisdom-Quotes/If you know yourself it will take care of the person" },
  { text: "If you read the Upanishads you will find all wisdom there", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/If you read the Upanishads you will find all wisdom there" },
  { text: "Ignorance uncertainty and wrong knowledge are the three...", source: "Kaivalya Navaneetam", slug: "Wisdom-Quotes/Ignorance uncertainty and wrong knowledge are the three bondages" },
  { text: "In the Vasishtam it is mentioned how to deal with...", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/In the Vasishtam it is mentioned how to deal with premonitions" },
  { text: "In truth there is no unalterable Dharma which the...", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/In truth there is no unalterable Dharma which the Tathagata could have taught" },
  { text: "Is there no way of escape from the miseries of this world", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Is there no way of escape from the miseries of this world" },
  { text: "It is that spiritual power which will make him transcend", source: "The Incredible Sai Baba", slug: "Wisdom-Quotes/It is that spiritual power which will make him transcend" },
  { text: "It was pointed out that Sri Bhagavan often said the...", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/It was pointed out that Sri Bhagavan often said the whole Vedanta" },
  { text: "Keep the mind steady by gently turning it inward", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Keep the mind steady by gently turning it inward" },
  { text: "Knowing yet unable to move a single cell aware of the...", source: "Dune", slug: "Wisdom-Quotes/Knowing yet unable to move a single cell aware of the entire universe" },
  { text: "Knowledge remains the ultimate sin the tree of knowledge...", source: "The New Dawn", slug: "Wisdom-Quotes/Knowledge remains the ultimate sin the tree of knowledge vs the tree of life" },
  { text: "Kunju Swami meets Bhagavan for the first time", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/Kunju Swami meets Bhagavan for the first time" },
  { text: "Learn how to be entirely unreceptive to sensations...", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Learn how to be entirely unreceptive to sensations arising from external forms" },
  { text: "Learn only how to avoid seeking for and attaching...", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Learn only how to avoid seeking for and attaching yourselves to anything" },
  { text: "Listening to me the same is possible you can listen and...", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/Listening to me the same is possible you can listen and be as you are" },
  { text: "Live in this world because this world gives a ripening", source: "The Perfect Master, Vol 1", slug: "Wisdom-Quotes/Live in this world because this world gives a ripening" },
  { text: "Lord Buddhas greatest grievance was that there is only...", source: "\"", slug: "Wisdom-Quotes/Lord Buddhas greatest grievance was that there is only suffering" },
  { text: "Making use of things does not defile you error arises...", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Making use of things does not defile you error arises from your regarding each thing as having a separate self" },
  { text: "Meditation depends on the strength of mind", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Meditation depends on the strength of mind" },
  { text: "Meditation is possible only if the ego is kept up", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Meditation is possible only if the ego is kept up" },
  { text: "Mind is like the void in which there is no confusion or evil", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Mind is like the void in which there is no confusion or evil" },
  { text: "Moral nobility and not social respectability", source: "The Path of Self Knowledge", slug: "Wisdom-Quotes/Moral nobility and not social respectability" },
  { text: "Mouna means continuous speech it is the speech of self", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/Mouna means continuous speech it is the speech of self" },
  { text: "My propositions serve as elucidations in darkness", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/My propositions serve as elucidations in darkness" },
  { text: "Negation of name and form reveals the Self", source: "The Ribhu Gita", slug: "Wisdom-Quotes/Negation of name and form reveals the Self" },
  { text: "No matter how exotic human civilization becomes no man...", source: "Dune", slug: "Wisdom-Quotes/No matter how exotic human civilization becomes no man ever outgrows the universe" },
  { text: "No one lights a lamp and hides it in a clay jar", source: "Bible - Book of Luke", slug: "Wisdom-Quotes/No one lights a lamp and hides it in a clay jar" },
  { text: "Non-action is unceasing activity", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Non-action is unceasing activity" },
  { text: "Non-duality means that only the Absolute is", source: "The Path of Self Knowledge", slug: "Wisdom-Quotes/Non-duality means that only the Absolute is" },
  { text: "Not only was the use of vichara not confined to advanced...", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/Not only was the use of vichara not confined to advanced seekers" },
  { text: "Nothing can be found to exist nothing is perceived as...", source: "Early Islamic Mysticism", slug: "Wisdom-Quotes/Nothing can be found to exist nothing is perceived as lacking" },
  { text: "On account of infinite consciousness all these...", source: "Yoga Vasistha", slug: "Wisdom-Quotes/On account of infinite consciousness all these experiences exist" },
  { text: "On the death of King George V devotees asked Bhagavan", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/On the death of King George V devotees asked Bhagavan" },
  { text: "One day when your mind has stopped functioning...", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/One day when your mind has stopped functioning completely you will know" },
  { text: "Only gratitude transforms and they are diametrically...", source: "The New Dawn", slug: "Wisdom-Quotes/Only gratitude transforms and they are diametrically opposite to desires" },
  { text: "Only lovers know scholars never to be a lover needs courage", source: "The New Dawn", slug: "Wisdom-Quotes/Only lovers know scholars never to be a lover needs courage" },
  { text: "Overcome passions by finding their source", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Overcome passions by finding their source" },
  { text: "Painful indeed is the process but later on everything...", source: "Siva Purana", slug: "Wisdom-Quotes/Painful indeed is the process but later on everything becomes auspicious from beginning to end" },
  { text: "People understand what knowledge means but they...", source: "In Search of the Miraculous", slug: "Wisdom-Quotes/People understand what knowledge means but they understand it differently" },
  { text: "Pouring God into God if you know what I mean", source: "Early Islamic Mysticism", slug: "Wisdom-Quotes/Pouring God into God if you know what I mean" },
  { text: "Rabia would douse the fires of hell and burn paradise so...", source: "Early Islamic Mysticism", slug: "Wisdom-Quotes/Rabia would douse the fires of hell and burn paradise so none love for any reason but sincere love" },
  { text: "Read the Gita sing it dance with it and allow it to...", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/Read the Gita sing it dance with it and allow it to transform you" },
  { text: "Realisation of Self requires absolute purity of mind", source: "Tripura Rahasya", slug: "Wisdom-Quotes/Realisation of Self requires absolute purity of mind" },
  { text: "Restrain each single thought from arising then the...", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/Restrain each single thought from arising then the Eighteen Sense Realms vanish" },
  { text: "Self alone is the reality all else is appearance", source: "Yoga Vasistha", slug: "Wisdom-Quotes/Self alone is the reality all else is appearance" },
  { text: "Sikhidhvaja renounces his kingdom for truth", source: "Tripura Rahasya", slug: "Wisdom-Quotes/Sikhidhvaja renounces his kingdom for truth" },
  { text: "Simply look at the flower and dont say anything", source: "Coming Home to Yourself", slug: "Wisdom-Quotes/Simply look at the flower and dont say anything" },
  { text: "Sorrow is all there is there is nothing other than sorrow", source: "\"", slug: "Wisdom-Quotes/Sorrow is all there is there is nothing other than sorrow" },
  { text: "Special instruction on the nature of bondage and liberation", source: "Kaivalya Navaneetam", slug: "Wisdom-Quotes/Special instruction on the nature of bondage and liberation" },
  { text: "Spiritual perfection changes even the body", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/Spiritual perfection changes even the body" },
  { text: "Sri Guru ocean of mercy can anyone drenched with Thy...", source: "Tripura Rahasya", slug: "Wisdom-Quotes/Sri Guru ocean of mercy can anyone drenched with Thy kindness ever be afflicted" },
  { text: "Start looking at things without the mind", source: "Coming Home to Yourself", slug: "Wisdom-Quotes/Start looking at things without the mind" },
  { text: "Take your power back and forget all this nonsense about...", source: "Silence of the Heart", slug: "Wisdom-Quotes/Take your power back and forget all this nonsense about a mind and a body" },
  { text: "Tattvaraya composed a bharani in honour of his Guru...", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/Tattvaraya composed a bharani in honour of his Guru Swarupananda" },
  { text: "Tell me O Swan your ancient tale from what land do you come", source: "Guru Granth Sahib", slug: "Wisdom-Quotes/Tell me O Swan your ancient tale from what land do you come" },
  { text: "That in which there is no manifestation of things", source: "The Ribhu Gita", slug: "Wisdom-Quotes/That in which there is no manifestation of things" },
  { text: "That in which there is the fullness of Consciousness...", source: "The Ribhu Gita", slug: "Wisdom-Quotes/That in which there is the fullness of Consciousness ever abide as That itself" },
  { text: "That is because surrender means the Self itself", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/That is because surrender means the Self itself" },
  { text: "That which IS is only one it is omnipresent and universal", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/That which IS is only one it is omnipresent and universal" },
  { text: "That which rises as I is the mind it is only the mind", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/That which rises as I is the mind it is only the mind" },
  { text: "The Almighty has no address nor location where He can be...", source: "\"", slug: "Wisdom-Quotes/The Almighty has no address nor location where He can be found" },
  { text: "The Buddha is really the creation of your own Mind", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/The Buddha is really the creation of your own Mind" },
  { text: "The Gateway of Non-Duality is your original Mind", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/The Gateway of Non-Duality is your original Mind" },
  { text: "The Guru kills without killing with the glance of His eyes", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/The Guru kills without killing with the glance of His eyes" },
  { text: "The Muni asked is it also stated that a Guru is necessary", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/The Muni asked is it also stated that a Guru is necessary" },
  { text: "The Self alone is real all else is imagined", source: "Tripura Rahasya", slug: "Wisdom-Quotes/The Self alone is real all else is imagined" },
  { text: "The Self alone remains after all illusion is destroyed", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/The Self alone remains after all illusion is destroyed" },
  { text: "The Self is not born and does not die", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/The Self is not born and does not die" },
  { text: "The Self is not somewhere far away you are always that", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/The Self is not somewhere far away you are always that" },
  { text: "The Self is realized by a certain mental activity", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/The Self is realized by a certain mental activity" },
  { text: "The Self remains untainted how can there be the...", source: "Kaivalya Navaneetam", slug: "Wisdom-Quotes/The Self remains untainted how can there be the distinctions of caste" },
  { text: "The Ultimate knowledge does not have any knowledge", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/The Ultimate knowledge does not have any knowledge" },
  { text: "The Vedas contain the truth but the truth cannot be...", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/The Vedas contain the truth but the truth cannot be expressed in words" },
  { text: "The appearance of a thing and its use differ in...", source: "Tripura Rahasya", slug: "Wisdom-Quotes/The appearance of a thing and its use differ in different states" },
  { text: "The archer sees the mark upon the path of the infinite", source: "The Prophet", slug: "Wisdom-Quotes/The archer sees the mark upon the path of the infinite" },
  { text: "The attempts of so-called social reformers are futile", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/The attempts of so-called social reformers are futile" },
  { text: "The best way is to be totally a watcher", source: "\"", slug: "Wisdom-Quotes/The best way is to be totally a watcher" },
  { text: "The common psychology of man is of loneliness", source: "\"", slug: "Wisdom-Quotes/The common psychology of man is of loneliness" },
  { text: "The cost of following Jesus", source: "Bible - Book of Luke", slug: "Wisdom-Quotes/The cost of following Jesus" },
  { text: "The divine Name chanting it one is transported across", source: "Guru Granth Sahib", slug: "Wisdom-Quotes/The divine Name chanting it one is transported across" },
  { text: "The doctrine of Advaita Non-duality taught by the...", source: "The Path of Self Knowledge", slug: "Wisdom-Quotes/The doctrine of Advaita Non-duality taught by the ancient Rishis" },
  { text: "The dualities of shame attraction and aversion", source: "\"", slug: "Wisdom-Quotes/The dualities of shame attraction and aversion" },
  { text: "The ego-consciousness is like the root of a plant", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/The ego-consciousness is like the root of a plant" },
  { text: "The first thing as I see you I see you miserable", source: "The New Dawn", slug: "Wisdom-Quotes/The first thing as I see you I see you miserable" },
  { text: "The force of her intense loyalty resisted the curse of...", source: "Tripura Rahasya", slug: "Wisdom-Quotes/The force of her intense loyalty resisted the curse of the Rishi" },
  { text: "The highest form of grace is silence", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/The highest form of grace is silence" },
  { text: "The idea of one Self being aware of another Self is absurd", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/The idea of one Self being aware of another Self is absurd" },
  { text: "The king remained motionless like a statue", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/The king remained motionless like a statue" },
  { text: "The mind is a bundle of thoughts arising from the I-thought", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/The mind is a bundle of thoughts arising from the I-thought" },
  { text: "The mind is only a bundle of thoughts", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/The mind is only a bundle of thoughts" },
  { text: "The more simple a life he leads the fewer needs he has", source: "The Incredible Sai Baba", slug: "Wisdom-Quotes/The more simple a life he leads the fewer needs he has" },
  { text: "The mystics concern is to quench his thirst", source: "Early Islamic Mysticism", slug: "Wisdom-Quotes/The mystics concern is to quench his thirst" },
  { text: "The one Consciousness called the mind has become the world", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/The one Consciousness called the mind has become the world" },
  { text: "The only freedom man has is to strive for and acquire jnana", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/The only freedom man has is to strive for and acquire jnana" },
  { text: "The quest of the Self alone is the direct path to right...", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/The quest of the Self alone is the direct path to right awareness" },
  { text: "The regret felt because of inability to fulfil desires...", source: "Swami Ishwarananda Giriji Maharaj", slug: "Wisdom-Quotes/The regret felt because of inability to fulfil desires becomes a Sadhus strength" },
  { text: "The sage does not teach by words but by his living presence", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/The sage does not teach by words but by his living presence" },
  { text: "The sage is unattached to anything or anybody", source: "Yoga Vasistha", slug: "Wisdom-Quotes/The sage is unattached to anything or anybody" },
  { text: "The sage sees no diversity in the Self", source: "Tripura Rahasya", slug: "Wisdom-Quotes/The sage sees no diversity in the Self" },
  { text: "The seed is the word of God", source: "Bible - Book of Luke", slug: "Wisdom-Quotes/The seed is the word of God" },
  { text: "The self alone exists as the supreme consciousness", source: "Yoga Vasistha", slug: "Wisdom-Quotes/The self alone exists as the supreme consciousness" },
  { text: "The sense of body is a thought the thought is of the mind", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/The sense of body is a thought the thought is of the mind" },
  { text: "The sleep state is free from thoughts and the Self shines", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/The sleep state is free from thoughts and the Self shines" },
  { text: "The state of Self-realisation must be beyond triputis", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/The state of Self-realisation must be beyond triputis" },
  { text: "The state we call realisation is simply being oneself", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/The state we call realisation is simply being oneself" },
  { text: "The things that keep us busy are interminable", source: "The Path of Self Knowledge", slug: "Wisdom-Quotes/The things that keep us busy are interminable" },
  { text: "The trance-state of prophecy is like no other vision", source: "Dune", slug: "Wisdom-Quotes/The trance-state of prophecy is like no other vision" },
  { text: "The universal human pain-body", source: "A New Earth", slug: "Wisdom-Quotes/The universal human pain-body" },
  { text: "The universe is just there that is the only way", source: "Dune", slug: "Wisdom-Quotes/The universe is just there that is the only way" },
  { text: "The universe is nothing but consciousness", source: "Tripura Rahasya", slug: "Wisdom-Quotes/The universe is nothing but consciousness" },
  { text: "The whole world is but a long dream", source: "Yoga Vasistha", slug: "Wisdom-Quotes/The whole world is but a long dream" },
  { text: "The world is a projection of the mind", source: "Tripura Rahasya", slug: "Wisdom-Quotes/The world is a projection of the mind" },
  { text: "The world is mental and it will shine as reality only in...", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/The world is mental and it will shine as reality only in the Light of Self" },
  { text: "The world which is afflicted with sorrow is of our own...", source: "Yoga Vasistha", slug: "Wisdom-Quotes/The world which is afflicted with sorrow is of our own making" },
  { text: "There are two answers to the question of knowledge", source: "In Search of the Miraculous", slug: "Wisdom-Quotes/There are two answers to the question of knowledge" },
  { text: "There has never been a single thing then where does dust...", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/There has never been a single thing then where does dust alight" },
  { text: "There is a remedy for sorrow", source: "\"", slug: "Wisdom-Quotes/There is a remedy for sorrow" },
  { text: "There is always a prevailing mystique in any civilization", source: "Dune", slug: "Wisdom-Quotes/There is always a prevailing mystique in any civilization" },
  { text: "There is no individuality left nevertheless suffering...", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/There is no individuality left nevertheless suffering has to be experienced" },
  { text: "There is no liberation for a person of mere book knowledge", source: "Vivekachudamani", slug: "Wisdom-Quotes/There is no liberation for a person of mere book knowledge" },
  { text: "There is no reaching the Self it is not outside you", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/There is no reaching the Self it is not outside you" },
  { text: "There is no use removing doubts one by one", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/There is no use removing doubts one by one" },
  { text: "There is only one God - the language, location, and...", source: "A Yogi's Insights into the Life & Miracles of Shirdi Sai Baba", slug: "Wisdom-Quotes/There is only one God - the language, location, and system may be different" },
  { text: "These are the seven states of ignorance", source: "Kaivalya Navaneetam", slug: "Wisdom-Quotes/These are the seven states of ignorance" },
  { text: "This course would have been better for every seeker", source: "Tripura Rahasya", slug: "Wisdom-Quotes/This course would have been better for every seeker" },
  { text: "This fear of facing the light is not a fear like other fears", source: "\"", slug: "Wisdom-Quotes/This fear of facing the light is not a fear like other fears" },
  { text: "This world-appearance is a confusion even as a blueness...", source: "Yoga Vasistha", slug: "Wisdom-Quotes/This world-appearance is a confusion even as a blueness in the sky is an optical illusion" },
  { text: "Those fools head for disaster who in their ignorance...", source: "Kaivalya Navaneetam", slug: "Wisdom-Quotes/Those fools head for disaster who in their ignorance neglect self-knowledge" },
  { text: "Thus spake Vasistha on the nature of liberation", source: "Yoga Vasistha", slug: "Wisdom-Quotes/Thus spake Vasistha on the nature of liberation" },
  { text: "Titov the Russian cosmonaut returned from space and...", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/Titov the Russian cosmonaut returned from space and declared there is no God" },
  { text: "To the degree that you turn away from attachments to the...", source: "Kaivalya Navaneetam", slug: "Wisdom-Quotes/To the degree that you turn away from attachments to the unreal" },
  { text: "Tu hi tu it is You only You", source: "\"", slug: "Wisdom-Quotes/Tu hi tu it is You only You" },
  { text: "Turn the mind inward and find out who the seer is", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Turn the mind inward and find out who the seer is" },
  { text: "Until the mind rests in God it must continue to wander", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Until the mind rests in God it must continue to wander" },
  { text: "Vidyeshvara Samhita on the four castes", source: "Vidyeshvara Samhita", slug: "Wisdom-Quotes/Vidyeshvara Samhita on the four castes" },
  { text: "We are the truth why should we run after it like the...", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/We are the truth why should we run after it like the musk deer" },
  { text: "What exists is the one Self only", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/What exists is the one Self only" },
  { text: "What great tapas this Ramaneswara Maharshi is doing", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/What great tapas this Ramaneswara Maharshi is doing" },
  { text: "What is concentration but the absolute consciousness of...", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/What is concentration but the absolute consciousness of reality" },
  { text: "What is the ego and how is it related to the Self", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/What is the ego and how is it related to the Self" },
  { text: "What measure is there to measure the Self", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/What measure is there to measure the Self" },
  { text: "Whatever has the impress of misery on it cannot be real", source: "Tripura Rahasya", slug: "Wisdom-Quotes/Whatever has the impress of misery on it cannot be real" },
  { text: "Whatever is happening is consciousness experiencing itself", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/Whatever is happening is consciousness experiencing itself" },
  { text: "When Bhagavan was in Virupaksha Cave Echamma came daily", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/When Bhagavan was in Virupaksha Cave Echamma came daily" },
  { text: "When I enquired what it was Bhagavan led me to see", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/When I enquired what it was Bhagavan led me to see" },
  { text: "When the eye of knowledge is opened one realizes one...", source: "Letters from Sri Ramanasramam", slug: "Wisdom-Quotes/When the eye of knowledge is opened one realizes one remains in the Self" },
  { text: "When the mind is purified consciousness shines forth", source: "Tripura Rahasya", slug: "Wisdom-Quotes/When the mind is purified consciousness shines forth" },
  { text: "When your mind sees no response it becomes weaker until...", source: "Silence of the Heart", slug: "Wisdom-Quotes/When your mind sees no response it becomes weaker until it disappears" },
  { text: "Where is the mind and where are the thoughts arising from it", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Where is the mind and where are the thoughts arising from it" },
  { text: "Who can deny the Self of anyone", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Who can deny the Self of anyone" },
  { text: "Why is Atma vichara necessary", source: "Talks with Ramana Maharshi", slug: "Wisdom-Quotes/Why is Atma vichara necessary" },
  { text: "With divine grace you can attain realisation even in an...", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/With divine grace you can attain realisation even in an instant" },
  { text: "Wonder of wonders beyond understanding is your strange fear", source: "Day by Day with Bhagavan", slug: "Wisdom-Quotes/Wonder of wonders beyond understanding is your strange fear" },
  { text: "Yes he has come back that was my doing", source: "Ramana Periya Purnam", slug: "Wisdom-Quotes/Yes he has come back that was my doing" },
  { text: "You are just like space because space is the beginning...", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/You are just like space because space is the beginning and end of everything" },
  { text: "You cannot be reasonable to become liberated", source: "Silence of the Heart", slug: "Wisdom-Quotes/You cannot be reasonable to become liberated" },
  { text: "You dont want to expand the brain you want to transcend...", source: "Silence of the Heart", slug: "Wisdom-Quotes/You dont want to expand the brain you want to transcend the brain" },
  { text: "You fly about like birds from another world", source: "Guru Vachaka Kovai", slug: "Wisdom-Quotes/You fly about like birds from another world" },
  { text: "You will recognize all minds as One and behold all...", source: "The Zen Teaching of Huang Po", slug: "Wisdom-Quotes/You will recognize all minds as One and behold all things as One" },
  { text: "Your hunger and thirst for bliss is absolutely fulfilled", source: "Consciousness and the Absolute", slug: "Wisdom-Quotes/Your hunger and thirst for bliss is absolutely fulfilled" },
  { text: "Your true identity is beyond all concepts", source: "The Nectar of Immortality", slug: "Wisdom-Quotes/Your true identity is beyond all concepts" },
  { text: "when dhyana becomes deep and firm it leads to sahaja sthiti", source: "sri ramana gita", slug: "Wisdom-Quotes/when dhyana becomes deep and firm it leads to sahaja sthiti" },
]
document.addEventListener("nav", () => {
  const container = document.getElementById("random-quote")
  if (!container) return

  const q = quotes[Math.floor(Math.random() * quotes.length)]
  const quoteEl = document.getElementById("random-quote-text")
  const sourceEl = document.getElementById("random-quote-source")
  const linkEl = document.getElementById("random-quote-link") as HTMLAnchorElement | null
  if (!quoteEl || !sourceEl) return

  quoteEl.textContent = q.text
  sourceEl.textContent = "\u2014 " + q.source
  if (linkEl) linkEl.href = "/" + q.slug
})
